Deploy: Implemented Zero Downtime Deployment

diff --git a/workflow/deploy.yml b/workflow/deploy.yml
--- a/workflow/deploy.yml
+++ b/workflow/deploy.yml
@@ -36,76 +36,110 @@ jobs:
       # Use the environment variables defined in the GitHub environment for the build process
       # CI=false to prevent React from treating the build as a CI environment which can cause warnings/errors
       - name: Build React app
-        env:
+        env: 
           REACT_APP_API_BASE_URL: ${{ vars.REACT_APP_API_BASE_URL }}
           REACT_APP_FAV_ICON: ${{ vars.REACT_APP_FAV_ICON }}
         run: |
-          echo "Bulding react app with API URL: $REACT_APP_API_BASE_URL"
-          CI=false npm run build
+              echo "Bulding react app with API URL: $REACT_APP_API_BASE_URL"
+              CI=false npm run build
 
-      # Create Deployment Marker File for Verification
+      # Create a marker file with the commit SHA to verify deployment later
       - name: Create Deployment marker file
         run: |
-          echo "${GITHUB_SHA}" > build/.deploy-marker
-
-      # Deploy to cPanel via SSH (Uses secrets that are defined in the repository settings)
-      - name: Check and Prepare Deployment Directory
+                  echo "${GITHUB_SHA}" > build/.deploy-marker
+      
+      # Upload in versions folder like versions/version-1, version-2
+      - name: Upload release
+        uses: appleboy/scp-action@v0.1.6
+        with:
+          host: ${{ secrets.CPANEL_HOST }}
+          username: ${{ secrets.CPANEL_USER }}
+          key: ${{ secrets.CPANEL_SSH_KEY }}
+          source: "build/*"
+          target: "/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}/versions/version-${{ github.run_number }}"
+          
+      # Check if the files are uploaded successfully by verifying the presence of the marker file on the server
+      - name: Check the Deployment marker file
         uses: appleboy/ssh-action@v1.0.3
         with:
-          host: ${{ secrets.CPANEL_HOST }}
-          username: ${{ secrets.CPANEL_USER }}
-          key: ${{ secrets.CPANEL_SSH_KEY }}
-          script: |
-            DEPLOY_PATH="/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}"
-            if [ ! -d "$DEPLOY_PATH" ]; then
-                mkdir -p "$DEPLOY_PATH"
-                echo "Created deployment directory: $DEPLOY_PATH"
-            else
-                echo "Deployment directory exists: $DEPLOY_PATH"
-            fi
-
-      # Upload built files to cPanel (build folder)
-      - name: Upload files to cPanel
-        uses: appleboy/scp-action@v0.1.7
+            host: ${{ secrets.CPANEL_HOST }}
+            username: ${{ secrets.CPANEL_USER }}
+            key: ${{ secrets.CPANEL_SSH_KEY }}
+            script: |
+                  DEPLOY_PATH="/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}/versions/version-${{ github.run_number }}/build"
+                  if [ -f "$DEPLOY_PATH/.deploy-marker" ]; then
+                      echo "Deployment marker file exists in $DEPLOY_PATH"
+                  else
+                      echo "Deployment marker file is missing in $DEPLOY_PATH"
+                      exit 1
+                  fi
+      # Set permissions to 755 for all files in the deployed directory to ensure they are accessible
+      - name: Set the permissions to the deployed files
+        uses: appleboy/ssh-action@v1.0.3
         with:
-          username: ${{ secrets.CPANEL_USER }}
-          host: ${{ secrets.CPANEL_HOST }}
-          key: ${{ secrets.CPANEL_SSH_KEY }}
-          source: build/*
-          target: "/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}"
+            host: ${{ secrets.CPANEL_HOST }}
+            username: ${{ secrets.CPANEL_USER }}
+            key: ${{ secrets.CPANEL_SSH_KEY }}
+            script: |
+                  DEPLOY_PATH="/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}/versions/version-${{ github.run_number }}/build"
+                  chmod -R 755 "$DEPLOY_PATH"
+                  echo "Set permissions to 755 for all files in $DEPLOY_PATH"
 
-      # Verify Deployment using the marker file
-      - name: Check Deployment
-        uses: appleboy/ssh-action@v0.1.7
+      # Activate the new release by updating the 'current' symlink to point to the new version and set permissions
+      - name: Activate Release and Set Current Symlink and Permissions
+        uses: appleboy/ssh-action@v1.0.3
         with:
-          username: ${{ secrets.CPANEL_USER }}
-          host: ${{ secrets.CPANEL_HOST }}
-          key: ${{ secrets.CPANEL_SSH_KEY }}
-          script: |
-            DEPLOY_PATH="/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}"
-            MARKER_FILE="$DEPLOY_PATH/build/.deploy-marker"
-            if [ -f "$MARKER_FILE" ] && grep -q "${GITHUB_SHA}" "$MARKER_FILE"; then
-                echo "Deployment successful. Files are present in $DEPLOY_PATH"
-            else
-                echo "Deployment Failed. No files found in $DEPLOY_PATH"
-                exit 1
-            fi
+            host: ${{ secrets.CPANEL_HOST }}
+            username: ${{ secrets.CPANEL_USER }}
+            key: ${{ secrets.CPANEL_SSH_KEY }}
+            script: |
+                  set -e
+                  cd "/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}"
+                  if [ ! -d "versions/version-${{ github.run_number }}" ]; then
+                      echo "Versions directory does not exist. Creating it now."
+                      mkdir -p "versions"
+                  fi
 
-      # Set Correct Permissions on Deployed Files
-      - name: Fix Permissions
-        uses: appleboy/ssh-action@v0.1.7
+                  ln -sfn "versions/version-${{ github.run_number }}/build" current
+                  chmod -R 755 "current"
+                  echo "Activated version-${{ github.run_number }} as the current release."
+      # Final check to ensure the deployment was successful by verifying the presence of the marker file in the 'current' directory
+      - name: Final Deployment Check
+        uses: appleboy/ssh-action@v1.0.3
         with:
-          username: ${{ secrets.CPANEL_USER }}
-          host: ${{ secrets.CPANEL_HOST }}
-          key: ${{ secrets.CPANEL_SSH_KEY }}
-          script: |
-            DEPLOY_PATH="/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}"
-            if [ -d "$DEPLOY_PATH" ] && [ ! -z "$DEPLOY_PATH" ] && [ "$DEPLOY_PATH" != "/home//" ]; then
-                chmod -R 755 "$DEPLOY_PATH"
-                echo "Permissions Fixed"
-                echo "Deployment Completed"
-            else
-                echo "Error: Invalid deployment path- $DEPLOY_PATH"
-                echo "Deployment Failed"
-                exit 1
-            fi
+            host: ${{ secrets.CPANEL_HOST }}
+            username: ${{ secrets.CPANEL_USER }}
+            key: ${{ secrets.CPANEL_SSH_KEY }}
+            script: |
+                  DEPLOY_PATH="/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}/current"
+                  MARKER_FILE="$DEPLOY_PATH/.deploy-marker"
+                  if [ -f "$MARKER_FILE" ] && grep -q "${GITHUB_SHA}" "$MARKER_FILE"; then
+                      echo "Deployment successful. Files are present in $DEPLOY_PATH"
+                  else
+                      echo "Deployment Failed. No files found in $DEPLOY_PATH"
+                      exit 1
+                  fi
+      # Clean up old versions, keep the latest 5 versions to save disk space and maintain a clean deployment directory
+      - name: Clean up old versions (Keep latest 5)
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+              host: ${{ secrets.CPANEL_HOST }}
+              username: ${{ secrets.CPANEL_USER }}
+              key: ${{ secrets.CPANEL_SSH_KEY }}
+              script: |
+                  set -e
+                  DEPLOY_DIR="/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}/versions"
+                  cd "$DEPLOY_DIR"
+                  
+                  if [ ! -d "$DEPLOY_DIR" ]; then
+                      echo "No versions directory found. Skipping cleanup."
+                      exit 0
+                  fi
+
+                  if [ "$DEPLOY_DIR" == "/" ] || [ -z "$DEPLOY_DIR" ] ||  [ "$DEPLOY_DIR" == "/home" ] || [ "$DEPLOY_DIR" == "/home/" ]; then
+                      echo "Error: Invalid deployment directory. Aborting cleanup."
+                      exit 1
+                  fi
+
+                  ls -1dt version-* | tail -n +6 | xargs -I {} rm -rf  "{}"
+                  echo "Cleaned up old versions, kept the latest 5 versions."
